import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  teams: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
    width:346,
  },
  firstTeam: {
    backgroundColor: '#c21b2c',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    flex: 1,
  },
  secondTeam: {
    backgroundColor: '#044fa1',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    flex: 1,
  },
  testHome: {
    fontWeight: 'bold',
    fontFamily: 'BebasNeue',
    color: '#FFFFFF',
    fontSize: 18,
    marginLeft: 5,
  },
  testAway: {
    fontWeight: 'bold',
    fontFamily: 'BebasNeue',
    color: '#FFFFFF',
    fontSize: 18,
    marginRight: 5,
  },
  messageBox: {
    fontWeight: 'bold',
    fontFamily: 'BebasNeue',
    color: '#FFFFFF',
    fontSize: 44,
    backgroundColor:'#044fa1',
    width:346,
    height: 164,
    borderWidth: 14,
    borderColor: '#303038',
    textAlign: 'center',
    justifyContent: 'center', 
    alignItems: 'center',
    zIndex: -1,
  },
  collect: {
    fontWeight: 'bold',
    fontFamily: 'BebasNeue',
    color: '#FFFFFF',
    fontSize: 28,
    backgroundColor:'#303038',
    width:318,
    height: 43,
    borderWidth: 2,
    borderColor: '#ffcc00',
    textAlign:  'center',
    position: 'relative',
    marginTop: -57,
  },
  total: {
    fontWeight: 'bold',
    fontFamily: 'BebasNeue',
    color: '#FFFFFF',
    fontSize: 30,
    backgroundColor:'transparent',
    transform: [{ rotate: '-3deg'}],
    marginTop: 50,
    marginBottom: 50,
  },
  sum: {
    fontWeight: 'bold',
    fontFamily: 'BebasNeue',
    color: '#FFFFFF',
    fontSize: 60,
    backgroundColor:'transparent',
    transform: [{ rotate: '-3deg'}],
    textShadowColor: '#ffcc00',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 2,
    marginRight: 10,
    marginBottom: -7,
  },
  exp: {
    fontWeight: 'bold',
    fontFamily: 'BebasNeue',
    color: '#FFFFFF',
    fontSize: 32,
    backgroundColor:'transparent',
    transform: [{ rotate: '-3deg'}],
    textShadowColor: '#32d900',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 2,
    marginRight: 10,
    marginBottom: -7,
  },
  sumCoins: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  expData: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 50,
    marginTop: 30,
  },
  triangle: {
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    marginTop: 28,
  },
  coins: {
    position: 'relative',
    marginTop: -40,
    marginLeft: 150,
  },
});

export default styles;
